//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingConstruction.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Housing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Housing()
        {
            this.Construction = new HashSet<Construction>();
        }
    
        public int ID { get; set; }
        public double Area { get; set; }
        public Nullable<int> RoomCount { get; set; }
        public string Address { get; set; }
        public decimal Price { get; set; }
        public int HousingTypeID { get; set; }
        public int StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Construction> Construction { get; set; }
        public virtual HousingType HousingType { get; set; }
        public virtual Status Status { get; set; }
    }
}
