//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingConstruction.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InProgressHousingInfo
    {
        public int HousingID { get; set; }
        public string HousingType { get; set; }
        public string HousingAddress { get; set; }
        public string HousingStatus { get; set; }
        public Nullable<System.DateTime> ConstructionStartDate { get; set; }
        public Nullable<System.DateTime> ConstructionEndDate { get; set; }
        public int DeveloperID { get; set; }
        public string DeveloperName { get; set; }
    }
}
