//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingConstruction.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public int ID { get; set; }
        public int WorkerID { get; set; }
        public int ConstructionID { get; set; }
        public System.DateTime ShiftDate { get; set; }
    
        public virtual Construction Construction { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
