//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingConstruction.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftSummary
    {
        public int ShiftID { get; set; }
        public Nullable<int> WorkerID { get; set; }
        public string FullName { get; set; }
        public int HousingID { get; set; }
        public string Address { get; set; }
        public string TypeName { get; set; }
        public string StatusName { get; set; }
        public Nullable<System.DateTime> ShiftDate { get; set; }
    }
}
