//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingConstruction.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerStatictics
    {
        public int ID { get; set; }
        public string WorkerFullName { get; set; }
        public Nullable<int> TotalShiftsWorked { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
    }
}
